Fixed Issue #229
google-deepmind/optax pull request #726
Opened 2024-01-21 23:49 UTC by amosyou

same as #435

2024-01-23 07:33 UTC, vroulet commented
Hello @amosyou,
And thanks again! As far as I can see, the optax-101 is just the README file put in notebook format. 
@fabianp had made a pass on the README file recently to correct diverse typos. Could you sync with main and use the newest version of the README?
(examples of typos are broken links as we changed the docs structure, you may not want to redo that :) )

2024-01-23 09:11 UTC, amosyou commented
sounds good! also wanted to take note of #663, @fabianp did we come to a consensus on whether to merge the notebooks? if so, happy to include those changes here in addition to adjusting for the typos

2024-01-23 09:37 UTC, fabianp commented
yes, ideally we would merge both notebooks. What you propose sounds great @amosyou !

2024-01-24 07:32 UTC, amosyou commented
@fabianp I decided to include both examples in the notebook (ie. linear model from quick_start, mlp from optax-101). Coming from someone who's new to optax, I found the linear model example really useful and easy to understand, but the mlp example is good for understanding the params as a dict. Let me know what you think!

2024-01-24 09:49 UTC, fabianp commented
sounds perfect. Let me know when I should take a look at the diff 😄

2024-01-24 19:00 UTC, amosyou commented
yup feel free to take a look!

2024-01-25 09:20 UTC, fabianp requested changes
A few cosmetic comments, thanks @amosyou !

2024-01-25 09:20 UTC, fabianp commented on docs/optax-101.ipynb
Instead of having a hard-coded link such as `https://optax.readthedocs.io/en/latest/api/common_losses.html`, use [sphinx references](https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#reference-roles) whenever possible.

So for example, instead of 
```The loss function (L2 Loss) comes from optax's [common loss functions](https://optax.readthedocs.io/en/latest/api/common_losses.html) via `optax.l2_loss()`.```
I would use ``` The loss function (L2 Loss) comes from optax's {doc}`losses <api/losses>` via {ref}`optax.l2_loss`.```

It's a bit uglier to read but the generated webpage is much nicer 😄

2024-01-25 09:20 UTC, fabianp commented on docs/optax-101.ipynb
The cell below `### Gradient Transformations` raises an exception `NameError: name 'init' is not defined`, please fix that

2024-01-30 07:30 UTC, fabianp commented
hey @amosyou , do you think you'll have cycles to implement the changes in the next couple of days? and if not, do you mind if I take over? I would really like to merge this before making any other changes to the documentation

2024-01-30 16:35 UTC, amosyou commented
yup! apologies for the delay, I can get the changes in today

2024-01-30 17:23 UTC, fabianp commented
thanks! And no rush, I just want this to be merged before I tackle other
doc improvements

On Tue, Jan 30, 2024 at 5:35 PM Amos You ***@***.***> wrote:

> yup! apologies for the delay, I can get the changes in today
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/google-deepmind/optax/pull/726#issuecomment-1917441075>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACDZB5PMHEQYOLPZD5BARLYREOOZAVCNFSM6AAAAABCEK7PU6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMJXGQ2DCMBXGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-01 01:05 UTC, amosyou commented on docs/optax-101.ipynb
the cell below `### Gradient Transformations` technically isn't meant to be run, it's pseudocode for the reader to understand the init/update functions. I changed it back to inline code snippet, would proceeding like this look better?

2024-02-01 01:49 UTC, amosyou commented on docs/optax-101.ipynb
For some reason the code cell under `### Gradient Transformation` is facing an error, but the code cell under `### Applying updates` is similar but no errors are found there

2024-02-01 09:41 UTC, fabianp approved these changes
Thanks @amosyou ! This document being the entry point for most users, it's an extremely important contribution that makes a big difference. Thanks again!

2024-02-01 09:48 UTC, amosyou commented
np! I had a couple comments under your code review, there might still be an error under one of the code cells. Also, I could either do it here or open a new issue to delete the other notebook in the gallery now that it's been combined

2024-02-01 10:01 UTC, fabianp commented
I've seen, no worries. I'll make a pass on it before merging :-)

2024-02-01 17:16 UTC, merged