Remove TF dependency in reduce_on_plateau example
google-deepmind/optax pull request #768
Opened 2024-02-04 06:17 UTC by mmhamdy

This PR removes Tensorflow as a dependency in `reduce_on_plateau.ipynb`, and uses only TFDS, with [grain](https://github.com/google/grain) for loading and preparing the dataset.

Addressing issue #656

2024-02-04 13:32 UTC, fabianp requested changes
This looks amazing! Way to go @mmhamdy! 🚀 

Just one thing, could you please remove the %pip install statements, and instead add these dependencies to the [pyproject.toml](https://github.com/google-deepmind/optax/blob/main/pyproject.toml) file, under section [docs].

2024-02-04 13:46 UTC, mmhamdy commented
Sure, much more cleaner this way.

2024-02-04 14:45 UTC, mmhamdy commented
Hey @fabianp, looks like there is a problem with python 3.9 and grain.

2024-02-04 17:42 UTC, fabianp commented
ouch! yeah, I'm seeing from https://github.com/google/grain/blob/main/pyproject.toml that they require Python 3.10 ....

2024-02-04 19:49 UTC, mmhamdy commented
ouch indeed! 😅 What do you think? should we stick to notebook downloads until we get rid of either TensorFlow or Python 3.9?

2024-02-05 07:52 UTC, fabianp commented
I'm unsure. Let me talk today with the other optax devs to see what they
think

On Sun, Feb 4, 2024, 19:50 Mohammed Hamdy ***@***.***> wrote:

> ouch indeed! 😅 What do you think? should we stick to notebook downloads
> until we get rid of either TensorFlow or Python 3.9?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/google-deepmind/optax/pull/768#issuecomment-1925895311>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACDZBYXEP4G7ZGONXUNHQDYR7Q6XAVCNFSM6AAAAABCYTNHXOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMRVHA4TKMZRGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-05 21:08 UTC, mmhamdy commented
Sounds great!

2024-02-07 11:43 UTC, fabianp commented
BTW I submitted a PR fixing python 3.9 errors: https://github.com/google/grain/pull/338

2024-02-07 12:31 UTC, mmhamdy commented
That's QUITE a PR! 😅😅

2024-02-07 13:16 UTC, fabianp commented
yeah, one thing that worries me a bit more about pygrain is that it it doesn't seem to build on OSX (tried and failed), and probably also Windows (haven't tried there). Before committing replacing TF with pygrain it would be important to make sure that those platforms are supported (just to say that it might take a bit before we merge these PRs unfortunately)

2024-02-07 15:55 UTC, mmhamdy commented
Well, replacing TensorFlow wasn't expected to be a walk in the park anyway 😃. But we've come a long way and I see that the people at pygrain are working daily on it.

2025-04-18 17:07 UTC, vroulet commented
For the record, in #1270 we removed this notebook (and others) from the docs building [configuration](https://github.com/google-deepmind/optax/blob/main/docs/conf.py) so we don't depend on tensorflow anymore during the continuous integration. 
This PR is still great to actually migrate the examples to grain for the sake of users learning how to use grain etc... And by the way, grain now supports mac os (not windows I believe but that's fine). So we could try merging this @mmhamdy if you want

2025-04-23 00:20 UTC, mmhamdy commented
hi @vroulet, yeah sure that would be great!

2026-04-30 09:19 UTC, rajasekharporeddy commented
Closing this PR since the TensorFlow dependency issue in `reduce_on_plateau` example is resolved with the PR #1616.

2026-04-30 09:19 UTC, closed without merging